{
 "title": "15min MRK prediction",
 "tags": [
  "Prediction",
  "Electricity"
 ],
 "time": { "from": "2025-09-24T15:15:00.000Z", "to": "2025-09-24T15:30:00.000Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "selectedYear",
    "label": "Year",
    "query": "SELECT DISTINCT year FROM year_month ORDER BY year DESC;"
   },
   {
    "name": "selectedMonth",
    "label": "Month",
    "query": "SELECT DISTINCT \"month\" FROM year_month WHERE \"year\" = ${selectedYear}"
   },
   {
    "name": "currentMonth",
    "query": "SELECT\nEXTRACT(MONTH FROM NOW() AT TIME ZONE 'Europe/Berlin')"
   },
   {
    "name": "currentYear",
    "query": "SELECT\nEXTRACT(YEAR FROM NOW() AT TIME ZONE 'Europe/Berlin')"
   },
   { "name": "MRK_Limit", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://guard331.azurewebsites.net/api/v1/data/alarm_event",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "request", "value": "{}" },
       { "key": "start", "value": "${__from:date:iso}" },
       { "key": "end", "value": "${__to:date:iso}" }
      ]
     }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"header-container\">\n  <img class=\"logo-desktop\" src=\"https://www.daitable.com/Daitable_logo_white.svg\" alt=\"Logo for desktop\">\n  <img class=\"logo-mobile\" src=\"/public/img/Daitable_main_logo.svg\" alt=\"Logo for mobile\">\n  <h1>Placeholder</h1>\n</div>"
   },
   "targets": [
    { "parser": "backend", "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "15-min data with prediction",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM predicted_15m_data"
    },
    {
     "data": "{\n  \"MRK_Limit\": ${MRK_Limit}\n}",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, taplast_metered + farmol_metered AS metered FROM predicted_15m_data ORDER BY timestamp"
    },
    {
     "data": "{\n  \"MRK_Limit\": ${MRK_Limit}\n}",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Reserved capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "${MRK_Limit}",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Predicted capacity usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, used_capacity AS metered FROM predicted_15m_data ORDER BY timestamp"
    },
    {
     "data": "{\n  \"MRK_Limit\": ${MRK_Limit}\n}",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Power reserve",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH data_to_calculate AS (\r\n  SELECT \r\n    \"timestamp\",\r\n    (taplast_metered + farmol_metered) AS metered,\r\n    'A' AS measurement\r\n  FROM \r\n    predicted_15m_data\r\n  WHERE taplast_metered IS NOT NULL AND farmol_metered IS NOT NULL\r\n),\r\ncalculated_data AS (\r\n  SELECT\r\n    COUNT(\"timestamp\") AS samples,\r\n    SUM(metered) AS metered\r\n  FROM \r\n    data_to_calculate\r\n)\r\nSELECT \r\n  ((${MRK_Limit} * 15) - metered) / (15 - samples + 0.0001) AS Power_Limit\r\nFROM calculated_data"
    },
    {
     "data": "{\n  \"MRK_Limit\": ${MRK_Limit}\n}",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Monitored transformers",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH raw_data AS (\r\n  SELECT\r\n    timestamp,\r\n    LAST_VALUE( timestamp )\r\n    OVER (\r\n      PARTITION BY measurement\r\n      ORDER BY timestamp) AS last_record,\r\n    LAST_VALUE((payload -> 'Active_Power_Total')::NUMERIC)\r\n    OVER (\r\n          PARTITION BY measurement\r\n          ORDER BY timestamp ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\r\n      ) AS Active_power_last,\r\n    measurement,\r\n    (payload -> 'Active_Power_Total')::NUMERIC AS Active_Power_Total\r\n  FROM electrometers\r\n  WHERE timestamp BETWEEN NOW() - INTERVAL '16 minutes' AND NOW()\r\n  AND FLOOR(EXTRACT(MINUTES FROM timestamp)::NUMERIC / 15.0) = FLOOR(EXTRACT(MINUTES FROM NOW())::NUMERIC / 15.0)\r\n  AND measurement IN ('TS01', 'TS02', 'TS03 - Farmol')\r\n  AND payload ? 'Active_Power_Total'\r\n),\r\naggregated_power_data AS (\r\n  SELECT\r\n  \ttime_bucket('1 hour'::INTERVAL, timestamp) AS hourly_bucket,\r\n  \tmeasurement,\r\n  \tmax(last_record) AS last_record,\r\n  \tMAX(ABS(Active_power_last)) AS Active_power_last,\r\n    AVG(ABS(Active_power_Total)) AS Active_Power_Avg\r\n  FROM raw_data\r\nGROUP BY\r\n  time_bucket('1 hour'::INTERVAL, timestamp),\r\n  measurement\r\n)\r\nSELECT \r\n  hourly_bucket,\r\n  measurement,\r\n  CASE\r\n    WHEN measurement = 'TS03 - Farmol' THEN 'Farmol'\r\n  ELSE 'Taplast'\r\n  END AS Company,\r\n  EXTRACT(EPOCH FROM (NOW() - last_record)) AS last_record_diff,\r\n  Active_power_last,\r\n  Active_power_Avg\r\n   FROM aggregated_power_data"
    }
   ]
  },
  {
   "title": "Monitored devices",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH raw_data AS (\r\n  SELECT\r\n    timestamp,\r\n    LAST_VALUE( timestamp )\r\n    OVER (\r\n      PARTITION BY measurement\r\n      ORDER BY timestamp) AS last_record,\r\n    LAST_VALUE((payload -> 'Active_Power_Total')::NUMERIC)\r\n    OVER (\r\n          PARTITION BY measurement\r\n          ORDER BY timestamp ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\r\n      ) AS Active_power_last,\r\n    measurement,\r\n    (payload -> 'Active_Power_Total')::NUMERIC AS Active_Power_Total,\r\n    tags ->> 'Transformer' AS Transformer\r\n  FROM electrometers\r\n  WHERE timestamp BETWEEN NOW() - INTERVAL '16 minutes' AND NOW()\r\n  AND FLOOR(EXTRACT(MINUTES FROM timestamp)::NUMERIC / 15.0) = FLOOR(EXTRACT(MINUTES FROM NOW())::NUMERIC / 15.0)\r\n  AND measurement NOT IN ('TS01', 'TS02', 'TS03 - Farmol')\r\n),\r\naggregated_power_data AS (\r\n  SELECT\r\n  \ttime_bucket('1 hour'::INTERVAL, timestamp) AS hourly_bucket,\r\n  \tmeasurement,\r\n  \tmax(last_record) AS last_record,\r\n  \tMAX(ABS(Active_power_last)) AS Active_power_last,\r\n    AVG(ABS(Active_power_Total)) AS Active_Power_Avg,\r\n    Transformer\r\n  FROM raw_data\r\nGROUP BY\r\n  time_bucket('1 hour'::INTERVAL, timestamp),\r\n  measurement,\r\n  Transformer\r\n)\r\nSELECT \r\n  hourly_bucket,\r\n  measurement,\r\n  transformer,\r\n  EXTRACT(EPOCH FROM (NOW() - last_record)) AS last_record_diff,\r\n  Active_power_last,\r\n  Active_power_Avg\r\n   FROM aggregated_power_data"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "15 minute averages per month - DEMO",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH time_selector AS (\r\n  SELECT\r\n  \t'${selectedYear}-${selectedMonth}-01 00:00:00 Europe/Berlin'::timestamptz - INTERVAL '10 hours' AS startTime\r\n  \t\r\n),\r\nvariables AS (\r\n  SELECT\r\n  \t${selectedYear} AS startYear,\r\n  \t${selectedMonth} AS startMonth\r\n),\r\nraw_data AS (\r\nSELECT\r\n  *\r\nFROM \r\n  active_power_15min, time_selector ts\r\nWHERE \r\n  \"timestamp\" BETWEEN ts.startTime AND ts.startTime + INTERVAL '32 days'\r\n  AND measurement IN ('TS01', 'TS02')\r\n),\r\naggregated_data AS (\r\n  SELECT\r\n    \"timestamp\",\r\n    SUM(active_power_total) AS active_power_total\r\n  FROM\r\n    raw_data, variables v\r\n  WHERE\r\n    EXTRACT(MONTH FROM \"timestamp\" AT TIME ZONE 'Europe/Berlin') = v.startMonth\r\n  GROUP BY\r\n    \"timestamp\"\r\n)\r\nSELECT \r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'hh24:mi') AS \"15min_interval\",\r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'DD. MM.') AS \"date\",\r\n  active_power_total\r\nFROM\r\n  aggregated_data"
    }
   ]
  },
  {
   "title": "15 minute averages per month - DEMO",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH time_selector AS (\r\n  SELECT\r\n  \t'${selectedYear}-${selectedMonth}-01 00:00:00 Europe/Berlin'::timestamptz - INTERVAL '10 hours' AS startTime\r\n  \t\r\n),\r\nvariables AS (\r\n  SELECT\r\n  \t${selectedYear} AS startYear,\r\n  \t${selectedMonth} AS startMonth\r\n),\r\nraw_data AS (\r\nSELECT\r\n  *\r\nFROM \r\n  active_power_15min, time_selector ts\r\nWHERE \r\n  \"timestamp\" BETWEEN ts.startTime AND ts.startTime + INTERVAL '32 days'\r\n  AND measurement NOT IN ('TS01', 'TS02')\r\n),\r\naggregated_data AS (\r\n  SELECT\r\n    \"timestamp\",\r\n    SUM(active_power_total) AS active_power_total\r\n  FROM\r\n    raw_data, variables v\r\n  WHERE\r\n    EXTRACT(MONTH FROM \"timestamp\" AT TIME ZONE 'Europe/Berlin') = v.startMonth\r\n  GROUP BY\r\n    \"timestamp\"\r\n)\r\nSELECT \r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'hh24:mi') AS \"15min_interval\",\r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'DD. MM.') AS \"date\",\r\n  active_power_total\r\nFROM\r\n  aggregated_data"
    }
   ]
  },
  {
   "title": "15 minute averages per month - Total",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH time_selector AS (\r\n  SELECT\r\n  \t'${selectedYear}-${selectedMonth}-01 00:00:00 Europe/Berlin'::timestamptz - INTERVAL '10 hours' AS startTime\r\n  \t\r\n),\r\nvariables AS (\r\n  SELECT\r\n  \t${selectedYear} AS startYear,\r\n  \t${selectedMonth} AS startMonth\r\n),\r\nraw_data AS (\r\nSELECT\r\n  *\r\nFROM \r\n  active_power_15min, time_selector ts\r\nWHERE \r\n  \"timestamp\" BETWEEN ts.startTime AND ts.startTime + INTERVAL '32 days'\r\n  AND measurement IN ('TS01', 'TS02', 'TS03 - Farmol')\r\n),\r\naggregated_data AS (\r\n  SELECT\r\n    \"timestamp\",\r\n    SUM(active_power_total) AS active_power_total\r\n  FROM\r\n    raw_data, variables v\r\n  WHERE\r\n    EXTRACT(MONTH FROM \"timestamp\" AT TIME ZONE 'Europe/Berlin') = v.startMonth\r\n  GROUP BY\r\n    \"timestamp\"\r\n)\r\nSELECT \r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'hh24:mi') AS \"15min_interval\",\r\n  TO_CHAR(\"timestamp\" AT TIME ZONE 'Europe/Berlin', 'DD. MM.') AS \"date\",\r\n  active_power_total\r\nFROM\r\n  aggregated_data"
    }
   ]
  }
 ]
}