{
 "title": "Device state analysis",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "Device",
    "query": "SELECT DISTINCT measurement FROM optimal_states_table"
   },
   {
    "name": "state",
    "label": "State",
    "query": "SELECT \n CASE WHEN tags->>'cluster' = 'idle' THEN 'Nečinný'\n WHEN tags->>'cluster' = 'working' THEN 'Pracovný'\n WHEN tags->>'cluster' = 'heating' THEN 'Zahrievanie'\n WHEN tags->>'cluster' = 'off' THEN 'Vypnutý'\nELSE \ntags->>'cluster' \nEND AS cluster \nFROM optimal_states_table\n WHERE measurement = '${machine}'"
   }
  ]
 },
 "panels": [
  { "type": "marcusolsson-dynamictext-panel", "gridPos": { "h": 3, "w": 21, "x": 0, "y": 0 } },
  {
   "title": "Actual device state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH raw AS (SELECT\r\n    s.*,\r\n    p.*\r\nFROM\r\n    statistics_table AS s,\r\n    json_to_record(payload::json) AS p(\r\n       \"Cluster\"  VARCHAR,\r\n        \"Total_Active_Power\" FLOAT\r\n    )\r\n  WHERE s.measurement = '${machine}' AND \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo() \r\n)\r\nSELECT\r\n    *\r\nFROM raw \r\nORDER BY timestamp ASC;"
    }
   ]
  },
  { "title": "Detailed state overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH raw AS (SELECT\n    s.*,\n    p.*\nFROM\n    statistics_table AS s,\n    json_to_record(payload::json) AS p(\n       \"Cluster\"  VARCHAR,\n        \"Total_Active_Power\" FLOAT\n    )\n  WHERE s.measurement = '${machine}' AND \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo() \n)\nSELECT\n    timestamp,\n    MAX(CASE WHEN r.\"Cluster\" = 'idle' THEN \"Total_Active_Power\"  ELSE NULL END)  AS \"Nečinný\",\n    MAX(CASE WHEN r.\"Cluster\" = 'working' THEN \"Total_Active_Power\"  ELSE NULL END) AS \"Práca\",\n    MAX(CASE WHEN r.\"Cluster\" = 'candidate_heating' THEN \"Total_Active_Power\"  ELSE NULL END)  AS \"Zahrievanie\",\n    MAX(CASE WHEN r.\"Cluster\" = 'off' THEN \"Total_Active_Power\"  ELSE NULL END)  AS \"Vypnutý\"\nFROM raw r\nGROUP BY timestamp\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "title": "Hours in actual state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH raw AS (SELECT\n    s.*,\n    p.*\nFROM\n    statistics_table AS s,\n    json_to_record(payload::json) AS p(\n        \"index\" INT,\n        \"Current_L1\" FLOAT,\n        \"Current_L2\" FLOAT,\n        \"Current_L3\" FLOAT,\n        \"Voltage_L1\" FLOAT,\n        \"Voltage_L2\" FLOAT,\n        \"Voltage_L3\" FLOAT,\n        \"Temperature\" FLOAT,\n        \"anomaly_flag\" BOOLEAN,\n        \"time_delta_s\" FLOAT,\n        \"Total_Current\" FLOAT,\n        \"idle_time_day\" INT,\n        \"idle_time_hour\" INT,\n        \"idle_time_week\" INT,\n       \"Cluster\"  VARCHAR,\n        \"Active_Power_L1\" FLOAT,\n        \"Active_Power_L2\" FLOAT,\n        \"Active_Power_L3\" FLOAT,\n        \"Power_Factor_L1\" FLOAT,\n        \"Power_Factor_L2\" FLOAT,\n        \"Power_Factor_L3\" FLOAT,\n        \"idle_time_month\" INT,\n        \"heating_time_day\" INT,\n        \"working_time_day\" INT,\n        \"heating_time_hour\" INT,\n        \"heating_time_week\" INT,\n        \"working_time_hour\" INT,\n        \"working_time_week\" INT,\n        \"Total_Active_Power\" FLOAT,\n        \"heating_time_month\" INT,\n        \"working_time_month\" INT,\n        \"Total_Current_Cheby\" FLOAT,\n        \"anomalies_day_count\" INT,\n        \"Total_Current_Butter\" FLOAT,\n        \"anomalies_week_count\" INT,\n        \"anomalies_month_count\" INT,\n        \"time_in_current_cluster\" INT,\n        \"time_since_last_anomaly\" INT,\n        \"Total_Active_Power_anomaly_zscore\" FLOAT\n    )\n  WHERE s.measurement = '${machine}'\n)\nSELECT\n    timestamp,\n    time_in_current_cluster / 60\nFROM raw r order by timestamp DESC LIMIT 1;\n\n"
    }
   ]
  },
  {
   "title": "Comparing measured values for ${machine} in state ${state}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH variable AS (\n  SELECT \n    CASE \n      WHEN '${state}' = 'Nečinný' THEN 'idle'\n      WHEN '${state}' = 'Zahrievanie' THEN 'heating'\n      WHEN '${state}' = 'Pracovný' THEN 'working'\n      WHEN '${state}' = 'Vypnutý' THEN 'off'\n      ELSE  '${state}' \n    END as state\n)\n  ,raw_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    tags ->> 'cluster' AS cluster,\n    payload -> 'Average_State' AS average_state,\n    payload -> 'Optimal_State' AS optimal_state,\n    payload -> 'Last_Values' AS current_state\n  FROM\n    optimal_states_table\n  WHERE\n    measurement = '${machine}'\n    AND tags ->> 'cluster' = (SELECT state FROM variable)\n),\nunpivoted_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L1' AS field_name,\n    CAST(average_state ->> 'Current_L1' AS FLOAT) AS average,\n    CAST(current_state ->> 'Current_L1' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Current_L1' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L2' AS field_name,\n    CAST(average_state ->> 'Current_L2' AS FLOAT),\n    CAST(current_state ->> 'Current_L2' AS FLOAT),\n    CAST(optimal_state ->> 'Current_L2' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L3' AS field_name,\n    CAST(average_state ->> 'Current_L3' AS FLOAT),\n    CAST(current_state ->> 'Current_L3' AS FLOAT),\n    CAST(optimal_state ->> 'Current_L3' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L1' AS field_name,\n    CAST(average_state ->> 'Voltage_L1' AS FLOAT),\n    CAST(current_state ->> 'Voltage_L1' AS FLOAT),\n    CAST(optimal_state ->> 'Voltage_L1' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L2' AS field_name,\n    CAST(average_state ->> 'Voltage_L2' AS FLOAT),\n    CAST(current_state ->> 'Voltage_L2' AS FLOAT),\n    CAST(optimal_state ->> 'Voltage_L2' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L3' AS field_name,\n    CAST(average_state ->> 'Voltage_L3' AS FLOAT),\n    CAST(current_state ->> 'Voltage_L3' AS FLOAT),\n    CAST(optimal_state ->> 'Voltage_L3' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L1' AS field_name,\n    CAST(average_state ->> 'Active_Power_L1' AS FLOAT),\n    CAST(current_state ->> 'Active_Power_L1' AS FLOAT),\n    CAST(optimal_state ->> 'Active_Power_L1' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L2' AS field_name,\n    CAST(average_state ->> 'Active_Power_L2' AS FLOAT),\n    CAST(current_state ->> 'Active_Power_L2' AS FLOAT),\n    CAST(optimal_state ->> 'Active_Power_L2' AS FLOAT)\n  FROM\n    raw_data\n  UNION\n  ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L3' AS field_name,\n    CAST(average_state ->> 'Active_Power_L3' AS FLOAT),\n    CAST(current_state ->> 'Active_Power_L3' AS FLOAT),\n    CAST(optimal_state ->> 'Active_Power_L3' AS FLOAT)\n  FROM\n    raw_data\n)\nSELECT\n  timestamp,\n  measurement,\n  cluster,\n  field_name,\n  average as \"Priemerná hodnota\",\n  current as \"Aktuálna hodnota\",\n  optimal as \"Optimálna hodnota\"\nFROM\n  unpivoted_data;"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH variable AS (\n  SELECT \n    CASE \n      WHEN '${state}' = 'Nečinný' THEN 'idle'\n      WHEN '${state}' = 'Zahrievanie' THEN 'heating'\n      WHEN '${state}' = 'Pracovný' THEN 'working'\n      WHEN '${state}' = 'Vypnutý' THEN 'off'\n      ELSE  '${state}' \n    END as state\n),\nraw_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    tags ->> 'cluster' AS cluster,\n    payload -> 'Average_State' AS average_state,\n    payload -> 'Optimal_State' AS optimal_state,\n    payload -> 'Last_Values' AS current_state\n  FROM\n    optimal_states_table\n  WHERE\n    measurement = '${machine}'\n    AND tags ->> 'cluster' = (SELECT state FROM variable)\n),\nunpivoted_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L1' AS field_name,\n    CAST(average_state ->> 'Current_L1' AS FLOAT) AS average,\n    CAST(current_state ->> 'Current_L1' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Current_L1' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L2' AS field_name,\n    CAST(average_state ->> 'Current_L2' AS FLOAT) AS average,\n    CAST(current_state ->> 'Current_L2' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Current_L2' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Prúd L3' AS field_name,\n    CAST(average_state ->> 'Current_L3' AS FLOAT) AS average,\n    CAST(current_state ->> 'Current_L3' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Current_L3' AS FLOAT) AS optimal\n  FROM\n    raw_data\n)\nSELECT\n  timestamp,\n  measurement,\n  cluster,\n  field_name,\n  average AS \"Priemerná hodnota\",\n  current AS \"Aktuálna hodnota\",\n  optimal AS \"Optimálna hodnota\"\nFROM\n  unpivoted_data;\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH variable AS (\n  SELECT \n    CASE \n      WHEN '${state}' = 'Nečinný' THEN 'idle'\n      WHEN '${state}' = 'Zahrievanie' THEN 'heating'\n      WHEN '${state}' = 'Pracovný' THEN 'working'\n      WHEN '${state}' = 'Vypnutý' THEN 'off'\n      ELSE  '${state}' \n    END as state\n),\nraw_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    tags ->> 'cluster' AS cluster,\n    payload -> 'Average_State' AS average_state,\n    payload -> 'Optimal_State' AS optimal_state,\n    payload -> 'Last_Values' AS current_state\n  FROM\n    optimal_states_table\n  WHERE\n    measurement = '${machine}'\n    AND tags ->> 'cluster' = (SELECT state FROM variable)\n),\nunpivoted_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L1' AS field_name,\n    CAST(average_state ->> 'Voltage_L1' AS FLOAT) AS average,\n    CAST(current_state ->> 'Voltage_L1' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Voltage_L1' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L2' AS field_name,\n    CAST(average_state ->> 'Voltage_L2' AS FLOAT) AS average,\n    CAST(current_state ->> 'Voltage_L2' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Voltage_L2' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Napätie L3' AS field_name,\n    CAST(average_state ->> 'Voltage_L3' AS FLOAT) AS average,\n    CAST(current_state ->> 'Voltage_L3' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Voltage_L3' AS FLOAT) AS optimal\n  FROM\n    raw_data\n)\nSELECT\n  timestamp,\n  measurement,\n  cluster,\n  field_name,\n  average AS \"Priemerná hodnota\",\n  current AS \"Aktuálna hodnota\",\n  optimal AS \"Optimálna hodnota\"\nFROM\n  unpivoted_data;\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH variable AS (\n  SELECT \n    CASE \n      WHEN '${state}' = 'Nečinný' THEN 'idle'\n      WHEN '${state}' = 'Zahrievanie' THEN 'heating'\n      WHEN '${state}' = 'Pracovný' THEN 'working'\n      WHEN '${state}' = 'Vypnutý' THEN 'off'\n      ELSE  '${state}' \n    END as state\n),\nraw_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    tags ->> 'cluster' AS cluster,\n    payload -> 'Average_State' AS average_state,\n    payload -> 'Optimal_State' AS optimal_state,\n    payload -> 'Last_Values' AS current_state\n  FROM\n    optimal_states_table\n  WHERE\n    measurement = '${machine}'\n    AND tags ->> 'cluster' = (SELECT state FROM variable)\n),\nunpivoted_data AS (\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L1' AS field_name,\n    CAST(average_state ->> 'Active_Power_L1' AS FLOAT) AS average,\n    CAST(current_state ->> 'Active_Power_L1' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Active_Power_L1' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L2' AS field_name,\n    CAST(average_state ->> 'Active_Power_L2' AS FLOAT) AS average,\n    CAST(current_state ->> 'Active_Power_L2' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Active_Power_L2' AS FLOAT) AS optimal\n  FROM\n    raw_data\n  UNION ALL\n  SELECT\n    timestamp,\n    measurement,\n    cluster,\n    'Činný výkon L3' AS field_name,\n    CAST(average_state ->> 'Active_Power_L3' AS FLOAT) AS average,\n    CAST(current_state ->> 'Active_Power_L3' AS FLOAT) AS current,\n    CAST(optimal_state ->> 'Active_Power_L3' AS FLOAT) AS optimal\n  FROM\n    raw_data\n)\nSELECT\n  timestamp,\n  measurement,\n  cluster,\n  field_name,\n  average AS \"Priemerná hodnota\",\n  current AS \"Aktuálna hodnota\",\n  optimal AS \"Optimálna hodnota\"\nFROM\n  unpivoted_data;\n"
    }
   ]
  },
  { "title": "Anomaly overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Clusters hours by days",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH raw AS (SELECT\n    s.*,\n    p.*\nFROM\n    statistics_table AS s,\n    json_to_record(payload::json) AS p(\n        \"idle_time_day\" INT,\n        \"heating_time_day\" INT,\n        \"working_time_day\" INT\n    )\n  WHERE s.measurement = '${machine}' AND date(s.timestamp) BETWEEN $__timeFrom()  AND $__timeTo() \n)\nSELECT\n    date(timestamp) as day,\n    MAX(idle_time_day) / 60  AS \"Nečinný\",\n    MAX(working_time_day) / 60 AS \"Práca\",\n    MAX(heating_time_day) / 60  AS \"Zahrievanie\"\nFROM raw r\nGROUP BY date(timestamp);\n\n"
    }
   ]
  },
  {
   "title": "Anomalies in time for device ${machine}",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "WITH raw AS (\n    SELECT\n        s.*,\n        p.*\n    FROM\n        statistics_table AS s,\n        json_to_record(payload::json) AS p(\n            \"anomaly_flag\" bool\n        )\n    WHERE\n        s.measurement = '${machine}'\n        AND DATE(s.timestamp) BETWEEN $__timeFrom()  AND $__timeTo()\n)\nSELECT \n        timestamp as current_day,\n        anomaly_flag::int anomaly_flag\n    FROM raw"
    }
   ]
  },
  {
   "title": "Anomalies count day and month",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "WITH raw AS (\n    SELECT\n        s.*,\n        p.*\n    FROM\n        statistics_table AS s,\n        json_to_record(payload::json) AS p(\n            \"anomaly_flag\" bool\n        )\n    WHERE\n        s.measurement = '${machine}'\n        AND DATE(s.timestamp) BETWEEN $__timeFrom()  AND $__timeTo() \n),\nprep AS (\n    SELECT DISTINCT\n        DATE(timestamp) as current_day,\n        SUM(anomaly_flag::int) OVER(PARTITION BY DATE(timestamp) ORDER BY timestamp) AS daily_anomaly_count,\n        SUM(anomaly_flag::int) OVER(PARTITION BY DATE_PART('month',timestamp) ORDER BY timestamp ROWS UNBOUNDED PRECEDING) AS monthly_anomaly_count\n    FROM raw\n)\nSELECT\n    current_day || ', mesiac: ' || DATE_PART('month',current_day) as \"Dátum\",\n    MAX(daily_anomaly_count) AS \"Denný počet anomálií\",\n    MAX(monthly_anomaly_count) AS \"Mesačný počet anomálií\"\nFROM prep group by current_day;"
    }
   ]
  },
  {
   "title": "Anomalies count day and week",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "WITH raw AS (\n    SELECT\n        s.*,\n        p.*\n    FROM\n        statistics_table AS s,\n        json_to_record(payload::json) AS p(\n            \"anomaly_flag\" bool\n        )\n    WHERE\n        s.measurement = '${machine}'\n        AND DATE(s.timestamp) BETWEEN $__timeFrom()  AND $__timeTo() \n),\nprep AS (\n    SELECT DISTINCT\n        DATE(timestamp) as current_day,\n        SUM(anomaly_flag::int) OVER(PARTITION BY DATE(timestamp) ORDER BY timestamp) AS daily_anomaly_count,\n        SUM(anomaly_flag::int) OVER(PARTITION BY DATE_PART('week',timestamp) ORDER BY timestamp ROWS UNBOUNDED PRECEDING) AS weekly_anomaly_count\n    FROM raw\n)\nSELECT\n    current_day || ', týŽden: ' || DATE_PART('week',current_day) as \"Dátum\",\n    MAX(daily_anomaly_count) AS \"Denný počet anomálií\",\n    MAX(weekly_anomaly_count) AS \"Týždenný počet anomálií\"\nFROM prep group by current_day;"
    }
   ]
  }
 ]
}